/*user: Primary Key(user_ID), user_name, role, age, state
catagory: catagory_ID, catagory_name, catagory_description
product: product_ID, product_name, sku, price, product_description, product_owner, prod_qnt
shelf: shelf_id, shelf_prod_id, shelf_prod_sku, shelf_prod_qnt
shopping_cart: cart_id, cart_user_ID, cart_prod_ID, cart_prod_qnt*/

DROP TABLE IF EXISTS THE_USER CASCADE;
DROP TABLE IF EXISTS CATEGORIES CASCADE;
DROP TABLE IF EXISTS PRODUCTS CASCADE;
DROP TABLE IF EXISTS SHELF CASCADE;
DROP TABLE IF EXISTS CART CASCADE;

CREATE TABLE THE_USER(
   USER_ID        SERIAL PRIMARY KEY, 
   USER_NAME      TEXT        NOT NULL,
   USER_ROLE 	  TEXT        NOT NULL,
   USER_AGE       INT         NOT NULL,
   USER_STATE	  TEXT        NOT NULL
);

CREATE TABLE CATEGORIES(
   CAT_ID         SERIAL PRIMARY KEY,
   CAT_NAME       TEXT        NOT NULL,
   CAT_DESCR      TEXT        NOT NULL
);

CREATE TABLE PRODUCTS(
   PROD_ID        SERIAL PRIMARY KEY,
   PROD_NAME      TEXT        NOT NULL,
   PROD_SKU       TEXT        NOT NULL,
   PROD_PRICE     DECIMAL     NOT NULL,
   PROD_DESCR     TEXT        NOT NULL,
   PROD_CAT_ID    INT REFERENCES CATEGORIES(CAT_ID),
   PROD_OWNER_ID  INT REFERENCES THE_USER(USER_ID)
);

CREATE TABLE SHELF(
   SHELF_ID         SERIAL PRIMARY KEY,
   SHELF_PROD_SKU   TEXT        NOT NULL,
   SHELF_PROD_QNT   INT         NOT NULL
);

CREATE TABLE CART( 
   CART_ID         INT, /*WILL BE THE USER_ID*/
   CART_PROD_ID    INT,
   CART_PROD_PRICE DECIMAL    NOT NULL
);

INSERT INTO THE_USER (USER_NAME, USER_ROLE, USER_AGE, USER_STATE) VALUES ( 'Trent', 'owner', 37, 'CA' );
INSERT INTO THE_USER (USER_NAME, USER_ROLE, USER_AGE, USER_STATE) VALUES ( 'Raj', 'Owner', 21, 'CA' );
INSERT INTO THE_USER (USER_NAME, USER_ROLE, USER_AGE, USER_STATE) VALUES ( 'Carlos', 'Owner', 27, 'CA' );

INSERT INTO THE_USER (USER_NAME, USER_ROLE, USER_AGE, USER_STATE) 
SELECT * FROM (SELECT 'Trent', 'Owner', 37, 'CA') AS tmp
WHERE NOT EXISTS (
    SELECT USER_NAME FROM THE_USER WHERE USER_NAME = 'Trent'
) LIMIT 1;

INSERT INTO THE_USER (USER_NAME, USER_ROLE, USER_AGE, USER_STATE) 
SELECT * FROM (SELECT 'New_Guy', 'Owner', 37, 'CA') AS tmp
WHERE NOT EXISTS (
    SELECT USER_NAME FROM THE_USER WHERE USER_NAME = 'New_Guy'
) LIMIT 1;



INSERT INTO CATEGORIES ( CAT_NAME, CAT_DESCR ) VALUES ( 'Food', 'Cooking Supplies' );
INSERT INTO CATEGORIES ( CAT_NAME, CAT_DESCR ) VALUES ( 'Cars', 'Automotive Accesseries' );
INSERT INTO CATEGORIES ( CAT_NAME, CAT_DESCR ) VALUES ( 'Books', 'Paperback' );

INSERT INTO CATEGORIES ( CAT_NAME, CAT_DESCR ) 
SELECT * FROM (SELECT  'Food', 'Different Cooking Supplies' ) AS tmp
WHERE NOT EXISTS (
    SELECT CAT_NAME FROM CATEGORIES WHERE CAT_NAME = 'Food' 
) LIMIT 1;

INSERT INTO PRODUCTS ( PROD_NAME, PROD_SKU, PROD_PRICE, PROD_DESCR, PROD_CAT_ID, PROD_OWNER_ID ) VALUES ( 'Blender', 'ABC123', 45.99, 'Hobart Blender', 1, 1 );
INSERT INTO PRODUCTS ( PROD_NAME, PROD_SKU, PROD_PRICE, PROD_DESCR, PROD_CAT_ID, PROD_OWNER_ID ) VALUES ( 'Blender', 'ABC123', 45.99, 'Hobart Blender', 1, 2 );
INSERT INTO PRODUCTS ( PROD_NAME, PROD_SKU, PROD_PRICE, PROD_DESCR, PROD_CAT_ID, PROD_OWNER_ID ) VALUES ( 'Blender', 'ABC123', 45.99, 'Hobart Blender', 1, 3 );



INSERT INTO PRODUCTS ( PROD_NAME, PROD_SKU, PROD_PRICE, PROD_DESCR, PROD_CAT_ID, PROD_OWNER_ID )
SELECT * FROM (SELECT 'Blender', 'ABC123', 4.99, 'Hobart Blender', 1, 1 ) AS tmp
WHERE NOT EXISTS (
    SELECT PROD_SKU FROM PRODUCTS WHERE PROD_SKU = 'ABC123' 
) LIMIT 1;


INSERT INTO SHELF ( SHELF_PROD_SKU, SHELF_PROD_QNT ) VALUES ( 'ABC123', 3 );
